### ISSUE TITLE
The project of  master branch can't work 

### ISSUE THREAD

**Issue by 123455151** [Verasl/BoatAttack#50]
I tried several branches,but no one can work.For the master branch,There are some problems.(Of course,I use the version of 2019.3.0a10)
1. Textures can't be loaded,like *.tif,even some *.png textures,and make the terrain and water no textures.
2. The variable defaultFoamRamp of WaterResources doesn't exist anymore,make the demo can't run.

**Comment by DongerGroup** [comment]
+1

**Comment by Rinsunsama** [comment]
same problems

**Comment by Nyro-Binag** [comment]
+1

**Comment by Nyro-Binag** [comment]
Solved - https://github.com/Verasl/BoatAttack/issues/38

**Comment by MingGuys** [comment]
can not work on 2020.2.1f1 too.redefinition error about "surfacedata"
